clickhouse-client --host localhost --port 9000 --user default --password --database appStoreData --input_format_allow_errors_num=1000 --date_time_input_format 'best_effort' \
 --query "
 INSERT INTO appStoreData.t_google_play
SELECT \`App Name\`,
       \`App Id\`,
       Category,
       Rating,
       toInt32OrZero(\`Rating Count\`),
       Installs,
       toInt64OrZero(\`Minimum Installs\`),
       toInt64OrZero(\`Maximum Installs\`),
       Free,
       Price,
       Currency,
       Size,
       \`Minimum Android\`,
       \`Developer Id\`,
       \`Developer Website\`,
       \`Developer Email\`,
       parseDateTimeBestEffortOrNull(replaceAll(Released, ',', ''), 'UTC'),
       parseDateTimeBestEffortOrNull(replaceAll(\`Last Updated\`, ',', ''), 'UTC'),
       \`Content Rating\`,
       \`Privacy Policy\`,
       \`Ad Supported\`,
       \`In App Purchases\`,
       \`Editors Choice\`,
       parseDateTimeBestEffortOrNull(replaceAll(\`Scraped Time\`, ',', ''), 'UTC')
FROM input(' \`App Name\`          String,
    \`App Id\`            String,
    Category            String,
    Rating              Float64,
    \`Rating Count\`      String,
    Installs            String,
    \`Minimum Installs\`  String,
    \`Maximum Installs\`   String,
    Free                Bool,
    Price               Float64,
    Currency            String,
    Size                String,
    \`Minimum Android\`   String,
    \`Developer Id\`      String,
    \`Developer Website\` String,
    \`Developer Email\`   String,
    Released            Nullable(String),
    \`Last Updated\` 	Nullable(String),
    \`Content Rating\`    String,
    \`Privacy Policy\`    String,
    \`Ad Supported\`      Bool,
    \`In App Purchases\`  Bool,
    \`Editors Choice\`    Bool,
    \`Scraped Time\` 	Nullable(String)')
    FORMAT CSVWithNames
" < Google-Playstore.csv