{
 "title": "App Stores Data",
 "time": { "from": "2010-02-01T00:00:00.000Z", "to": "2021-06-01T00:00:00.000Z" },
 "panels": [
  {
   "title": "Average Rating",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nselect distinct Category,\n                avg_rat as `Average Rating` from\n     (SELECT Distinct Category,\n            sum(mul_rat)  OVER (PARTITION BY Category) as sum_mul_ratings_cat,\n             Num_Ratings,\n             Average_Rating * Num_Ratings as mul_rat,\n            sum(Num_Ratings) OVER (PARTITION BY Category) as sum_num_ratings_cat,\n            sum_mul_ratings_cat / sum_num_ratings_cat as avg_rat\n     FROM  appStoreData.t_released_cat_bytes_app);\n"
    }
   ]
  },
  {
   "title": "Largest Apps by Year and Category",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "\nselect * from (\n      SELECT toYear(Released) as Year,\n             Category,\n             row_number() OVER (PARTITION BY Year, Category ORDER BY Year ASC, Category ASC, Size_Bytes DESC) as Size_Rank,\n             formatReadableSize(Size_Bytes) as Size,\n             Size_Bytes,\n             App_Name,\n             App_Id\n      FROM appStoreData.t_released_cat_bytes_app\n      GROUP BY Year,\n               Category,\n               Size_Bytes,\n               App_Id,\n               App_Name\n      ORDER BY Year DESC, Size_Bytes DESC)\nwhere Size_Rank <= 10\n  and Year > 1970\n    AND Size_Bytes > 0;\n\n"
    }
   ]
  },
  {
   "title": "Number of Apps Released by Month",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "\nSELECT distinct toDateTime(toStartOfMonth(Released)) as Released,\n                count(*) OVER (PARTITION BY Released, Category) as `Num Released`,\n                Category\nFROM appStoreData.t_released_cat_bytes_app\nwhere toYear(Released) > 1970\nORDER BY Released DESC;"
    }
   ]
  },
  {
   "title": "Distribution of Size of Health Apps in Bytes",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT Released,\n       Size_Bytes\nFROM appStoreData.t_released_cat_bytes_app\nWHERE Category = 'Health'\nand Size_Bytes > 0\nand toYear(Released) > 1970\nORDER BY rand()\nLIMIT 1000;"
    }
   ]
  },
  {
   "title": "Number of Music Apps Released by Month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "\nSELECT distinct toDateTime(toStartOfMonth(Released)) as Released,\n                count(*) OVER (PARTITION BY Released) as `Num Released`\nFROM appStoreData.t_released_cat_bytes_app\nwhere toYear(Released) > 1970\nand Category = 'Music'\nORDER BY Released DESC;"
    }
   ]
  },
  {
   "title": "Distribution of Size of Music Apps in Bytes",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT Released,\n       Size_Bytes\nFROM appStoreData.t_released_cat_bytes_app\nWHERE Category = 'Music'\nand Size_Bytes > 0\nand toYear(Released) > 1970\nORDER BY rand()\nLIMIT 1000;"
    }
   ]
  },
  {
   "title": "Number of Games Released by Month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "\nSELECT distinct toDateTime(toStartOfMonth(Released)) as Released,\n                count(*) OVER (PARTITION BY Released, Category) as `Num Released`\nFROM appStoreData.t_released_cat_bytes_app\nwhere toYear(Released) > 1970\nand Category = 'Games'\nORDER BY Released DESC, Category DESC;"
    }
   ]
  },
  {
   "title": "Distribution of Size of Game Apps in Bytes",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT Released,\n       Size_Bytes\nFROM appStoreData.t_released_cat_bytes_app\nWHERE Category = 'Games'\nand Size_Bytes > 0\nand toYear(Released) > 1970\nORDER BY rand()\nLIMIT 1000;"
    }
   ]
  }
 ]
}