version: "3.9"
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
      - "9004:9004"
    ulimits:
        nofile:
            soft: 262144
            hard: 262144
    user: '0'
    volumes:
      - ./init/create/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./init/config.xml:/etc/clickhouse-server/config.xml 
    # environment:
    #   - CLICKHOUSE_DB "appStoreData"
    #   - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT "1"
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - clickhouse
    ports:  
      - "3000:3000"
    user: '0'
    volumes:
      - ./grafana-storage:/var/lib/grafana
    # environment:
    #   GF_INSTALL_PLUGINS: "grafana-clickhouse-datasource"
    #   GF_SECURITY_ADMIN_USER: "admin"
    #   GF_SECURITY_ADMIN_PASSWORD: "admin1"
