version: "3.9"
services:
  clickhouse2:
    image: clickhouse/clickhouse-server
    container_name: clickhouse2
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
      - "9004:9004"
    ulimits:
        nofile:
            soft: 262144
            hard: 262144
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - ./init/config.xml:/etc/clickhouse-server/config.xml 
    environment:
      - CLICKHOUSE_DB=appStoreData 
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1 

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - clickhouse2
    ports:
      - "3000:3000"
    user: '0'
    volumes:
      - ./grafana-storage:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: "grafana-piechart-panel,grafana-clickhouse-datasource"
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin1"
